baseurl = "https://cloudautomation.pharriso.co.uk"
theme="material-design"
languageCode = "en-us"
title = "Cloud and Automation"
paginate = 9
publishDir = "docs"

[params]
  description = "This blog focuses mainly on Red Hat products in the Cloud and Automation space. I am currently working as a Solution Architect for Red Hat in the UK."
  twitter = "patharrison_esq" # optional
  github = "pharriso" # optional
  linkedin = "pharriso" # optional
  #headerCover = "images/background.jpg"
